### ISSUE TITLE
Active_BS in I1_2p5 or I1_2p4 ?

### ISSUE THREAD

**Issue by lumliolum** [malrabeiah/DL-Massive-MIMO#1]
After reading the ReadMe.md [here](https://github.com/malrabeiah/DL-Massive-MIMO/tree/master/ChannelMapping) , for I1_2p5 or I1_2p4 scenario , what's the value of Active_BS out of 64 Basestations ?

The parameter is not mentioned here : 
![image](https://user-images.githubusercontent.com/28287182/64844726-2044ec80-d626-11e9-8f7d-a80a89808724.png)

**Comment by malrabeiah** [comment]
Hello @Saisuchith ,

Sorry it took me a while to reply.

Actually, "Number of BSs" is "Active BSs" in DeepMIMO. Sorry for the inconvenience. It was a typo. This number works with both scenarios I1_2p4 and I1_2p5.

I have updated the ReadMe file accordingly.

Thank you very much for pointing that out.
