### ISSUE TITLE
Unable to run the dataset generator

### ISSUE THREAD

**Issue by spranjal25** [malrabeiah/DL-Massive-MIMO#4]
Hi @malrabeiah,

I'm a newbie into DL with Matlab, could you please help me and @rashiisingh with how exactly do we need to proceed with:
1. Generating the dataset, I've tried what is stated in [deepmimo.net](https://deepmimo.net/versions/v2-matlab/), but it doesn't seem to give us any output, 
2. What should I put in the .mat format, the file apparently is either not being generated (in the above step) or I'm missing something here.

Please help.

**Comment by malrabeiah** [comment]
Hello @spranjal25,

Check the notes in the script “dataPrep.m.” They explain the expected array structure for the wireless channels. This structure is not the same as that coming out of DeepMIMO; you should generate the DeepMIMO data, and, then, structure the channels in the same array structure described in “dataPrep.m”

What I suggest here is that you do the following:
1) Familiarize yourself with MATLAB structures and arrays.
2) Visit the DeepMIMO website and learn how to generate a dataset.
3) Re-structure the dataset in the format described in “dataPrep.m”
